/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        primary: "#e8613a",
        "primary-dark": "#c94f2c",
        ink: "#1a1a1a",
        "on-primary": "#ffffff",
        canvas: "#ffffff",
        "canvas-cream": "#faf7f2",
        "surface-maroon": "#4a201f",
        "surface-maroon-elevated": "#5c2b26",
        "accent-pink-bar": "#f2a8b8",
        "accent-blush": "#f6d9c9",
        "shade-20": "#e5e5e5",
        "shade-30": "#d4d4d4",
        "shade-40": "#a3a3a3",
        "shade-50": "#767676",
        "shade-60": "#525252",
        hairline: "#e8e8e8",
        "success-green": "#1e7d32",
        "link-slate": "#5c6b7a",
        "price-strike": "#9a9a9a",
        accent: "#1a1a1a",
        border: "#e8e8e8",
      },
      fontFamily: {
        sans: ['"Helvetica Neue"', "Arial", "sans-serif"],
        serif: ['"Big Caslon"', '"Cormorant Garamond"', "Georgia", "serif"],
        script: ['"Big Caslon"', '"Cormorant Garamond"', "Georgia", "serif"],
      },
      fontSize: {
        "display-hero": ["72px", { lineHeight: "0.95", fontWeight: "800", letterSpacing: "-0.5px" }],
        "script-lead": ["30px", { lineHeight: "1.1", fontWeight: "400", fontStyle: "italic" }],
        "heading-section": ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "heading-md": ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        "nav-label": ["13px", { lineHeight: "1.2", fontWeight: "500", letterSpacing: "1px" }],
        "product-title": ["15px", { lineHeight: "1.4", fontWeight: "600" }],
        "product-caption": ["12px", { lineHeight: "1.4", fontWeight: "400", letterSpacing: "0.2px" }],
        "price-current": ["16px", { lineHeight: "1.3", fontWeight: "700" }],
        "price-strike": ["14px", { lineHeight: "1.3", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
      },
      letterSpacing: {
        tracked: "1px",
        "tracked-wide": "0.2px",
      },
      borderRadius: {
        xs: "4px",
        sm: "6px",
        md: "8px",
        lg: "16px",
        pill: "9999px",
      },
      spacing: {
        xxs: "2px",
        xs: "4px",
        sm: "8px",
        md: "12px",
        lg: "16px",
        xl: "24px",
        xxl: "32px",
        huge: "64px",
      },
    },
  },
  plugins: ["@tailwindcss/forms"],
};
